#!/usr/bin/env python3
"""
Generate src/tls_root_ca.h — the trust anchors the OTA updater will verify
against when BRINGUP_TLS_VERIFY=1.

    python3 scripts/fetch_root_ca.py github.com objects.githubusercontent.com \
                                     release-assets.githubusercontent.com \
        > src/tls_root_ca.h

Why more than one host: GitHub redirects release downloads ACROSS HOSTS, and
those hosts do not share a root. Pin only github.com's and the download fails
at the redirect — after the check appeared to work, which is the worst kind of
bug. Pass every host the updater can end up talking to.

mbedtls parses concatenated PEMs into a chained trust list, so several roots in
one string is exactly how you express "trust any of these".

⚠️  WHAT YOU ARE COMMITTING TO
Pinning is a promise that outlives your attention. If a pinned root is retired
or expires, every deployed device loses its update path PERMANENTLY — you
cannot ship the fix, because shipping the fix is the thing that broke. So:

  * pin ROOTS (decades of validity), never leaves or intermediates (months)
  * the script prints each certificate's expiry — read it
  * self-hosting with your OWN CA is strictly better: one root, 20-year
    validity, and you control the rotation. See docs/OTA.md.

Requires the `openssl` CLI.
"""
import re
import subprocess
import sys
from datetime import datetime, timezone

PEM_RE = re.compile(
    r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", re.S
)


def chain_for(host, port=443):
    """Every certificate the server presents, leaf first."""
    try:
        out = subprocess.run(
            ["openssl", "s_client", "-connect", f"{host}:{port}",
             "-servername", host, "-showcerts"],
            input=b"", capture_output=True, timeout=30,
        ).stdout.decode("utf-8", "replace")
    except FileNotFoundError:
        sys.exit("❌ openssl not found — install it or supply PEMs by hand")
    except subprocess.TimeoutExpired:
        sys.exit(f"❌ timed out connecting to {host}")
    pems = PEM_RE.findall(out)
    if not pems:
        sys.exit(f"❌ no certificates returned by {host}")
    return pems


def describe(pem):
    """(subject, issuer, notAfter, is_ca) for a PEM."""
    out = subprocess.run(
        ["openssl", "x509", "-noout", "-subject", "-issuer", "-enddate", "-ext",
         "basicConstraints"],
        input=pem.encode(), capture_output=True,
    ).stdout.decode()
    get = lambda k: next(
        (l.split("=", 1)[1].strip() for l in out.splitlines() if l.startswith(k)), "?"
    )
    is_ca = "CA:TRUE" in out
    return get("subject"), get("issuer"), get("notAfter"), is_ca


def main():
    hosts = sys.argv[1:]
    if not hosts:
        sys.exit(__doc__)

    seen, blocks, notes = set(), [], []
    for host in hosts:
        chain = chain_for(host)
        top = chain[-1]                     # highest cert the server sends
        subject, issuer, expiry, is_ca = describe(top)
        self_signed = subject == issuer

        if not is_ca:
            notes.append(
                f"{host}: the top certificate is NOT a CA (no CA:TRUE). That is a "
                f"leaf — pinning it will break at the next certificate renewal, "
                f"usually within months. Do not ship this."
            )
        elif not self_signed:
            # Almost always a CROSS-SIGNED root rather than an intermediate:
            # CAs present the variant signed by an older, more widely trusted
            # root so that ancient clients can still build a chain. It works
            # fine as a trust anchor — mbedtls anchors on whatever you give it,
            # self-signed or not — but the CA's own self-signed root usually
            # lives longer, so prefer that if you can get it.
            notes.append(
                f"{host}: top certificate is a CA but not self-signed "
                f"(issued by {issuer}). That is normally the CROSS-SIGNED "
                f"variant of a root, not an intermediate — it works as an "
                f"anchor, but the CA's self-signed root usually has a longer "
                f"life. Check the expiry above before relying on this."
            )
        if top in seen:
            notes.append(f"{host}: shares a root already included — deduped.")
            continue
        seen.add(top)
        blocks.append((host, subject, expiry, self_signed, top))
        print(f"  {host}: {subject}  (expires {expiry})", file=sys.stderr)

    print("#pragma once")
    print("//")
    print("// GENERATED by scripts/fetch_root_ca.py — do not edit by hand.")
    print("// Trust anchors for the OTA updater (BRINGUP_TLS_VERIFY=1).")
    print("//")
    print("// Hosts covered:")
    for host, subject, expiry, self_signed, _ in blocks:
        kind = "self-signed root" if self_signed else "CA, cross-signed (see notes)"
        print(f"//   {host}")
        print(f"//     {subject}")
        print(f"//     expires {expiry}   [{kind}]")
    if notes:
        print("//")
        print("// WARNINGS:")
        for n in notes:
            print(f"//   - {n}")
    print("//")
    print("// When the earliest expiry above approaches, deployed devices will")
    print("// lose their update path. Re-run this script and ship a new build")
    print("// BEFORE that date, not after.")
    print("//")
    print(f"// Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d')} against: "
          f"{', '.join(hosts)}")
    print()
    print("static const char BRINGUP_TLS_ROOT_CA_PEM[] =")
    for host, subject, _, _, pem in blocks:
        print(f'    // {host} — {subject}')
        for line in pem.splitlines():
            print(f'    "{line}\\n"')
    print("    ;")


if __name__ == "__main__":
    main()
